databases:
  - name: django_poetry_example
    databaseName: django_poetry_example
    user: django_poetry_example

services:
  - type: web
    name: django_poetry_example
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_poetry_example.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_poetry_example
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4